language: python

# Use container-based infrastructure
sudo: false

matrix:
  include:
   - env: TOXENV=py27-dj110-sqlite
     python: 2.7
   - env: TOXENV=py34-dj110-sqlite
     python: 3.4
   - env: TOXENV=py35-dj110-sqlite
     python: 3.5
   - env: TOXENV=py27-dj111-sqlite
     python: 2.7
   - env: TOXENV=py35-dj111-sqlite
     python: 3.5
   - env: TOXENV=py36-dj111-sqlite
     python: 3.6
   - env: TOXENV=py34-dj20-sqlite
     python: 3.4
   - env: TOXENV=py35-dj20-sqlite
     python: 3.5
   - env: TOXENV=py36-dj20-sqlite
     python: 3.6
   - env: TOXENV=py27-dj110-postgres
     python: 2.7
   - env: TOXENV=py34-dj110-postgres
     python: 3.4
   - env: TOXENV=py35-dj110-postgres
     python: 3.5
   - env: TOXENV=py27-dj111-postgres
     python: 2.7
   - env: TOXENV=py35-dj111-postgres
     python: 3.5
   - env: TOXENV=py36-dj111-postgres
     python: 3.6
   - env: TOXENV=py34-dj20-postgres
     python: 3.4
   - env: TOXENV=py35-dj20-postgres
     python: 3.5
   - env: TOXENV=py36-dj20-postgres
     python: 3.6

install:
  - pip install tox
  - createdb modelcluster

script:
  tox
